# Generated by Django 6.0.3 on 2026-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0025_invoicecommentattachment_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoversetting',
            name='call_due_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoversetting',
            name='email_due_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoversetting',
            name='whatsapp_due_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
