# Generated by Django 6.0.3 on 2026-08-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0028_debtornotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='wati_template_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
