# Generated by Django 6.0.3 on 2026-08-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0029_messagetemplate_wati_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtorcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='xero_app.debtorcomment'),
        ),
        migrations.AddField(
            model_name='debtornotice',
            name='kind',
            field=models.CharField(choices=[('comment', 'Comment'), ('reply', 'Reply'), ('allocation', 'Allocation')], default='comment', max_length=20),
        ),
    ]
