# Generated by Django 6.0.3 on 2026-08-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0030_debtorcomment_parent_debtornotice_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtornotice',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='xero_app.debtorcomment'),
        ),
    ]
