# Generated by Django 6.0.3 on 2026-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0032_backfill_notice_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_id', models.CharField(max_length=64)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=64)),
                ('contact_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('returned_by', models.CharField(blank=True, default='', max_length=255)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tenant_id', 'invoice_id')},
            },
        ),
    ]
