# Generated by Django 6.0.3 on 2026-09-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0033_handoverreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='active_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='active_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
