# Generated by Django 6.0.3 on 2026-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0034_messagetemplate_active_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtorcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtorcomment',
            name='deleted_by_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
