# Generated by Django 6.0.3 on 2026-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0035_debtorcomment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='wati_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='wati_category',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
