# Generated by Django 6.0.3 on 2026-09-28 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0036_messagetemplate_wati_body_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('keywords', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='recoveredinvoice',
            name='allocated_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_recoveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoveredinvoice',
            name='allocated_admin_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='writeoffinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='DebtorClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('contact_id', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('set_by', models.CharField(blank=True, max_length=255)),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='xero_app.debtorcategory')),
            ],
            options={
                'unique_together': {('tenant_id', 'contact_id')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=64)),
                ('day', models.DateField()),
                ('contact_id', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('administrator_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active collections'), ('handover', 'Handover'), ('legal', 'With attorneys'), ('closed', 'Closed')], max_length=10)),
                ('invoice_count', models.IntegerField(default=0)),
                ('not_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('b0_30', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('b31_60', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('b61_90', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('b91_120', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('b120_plus', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_days_past_due', models.IntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now=True)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'day'], name='xero_app_po_tenant__fbb4d6_idx')],
                'unique_together': {('tenant_id', 'day', 'contact_id', 'status')},
            },
        ),
    ]
