# Generated by Django 6.0.3 on 2026-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legal_access',
            field=models.BooleanField(default=False, help_text='Can work matters on the Lawyers page (in addition to their role).', verbose_name='Lawyers page access'),
        ),
    ]
