# Generated by Django 6.0.3 on 2026-08-13 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_legal_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_label', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('change', 'Data change'), ('login', 'Signed in'), ('logout', 'Signed out'), ('login_failed', 'Failed sign-in')], db_index=True, default='change', max_length=15)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('url_name', models.CharField(blank=True, default='', max_length=80)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('params_json', models.TextField(blank=True, default='')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_7b1069_idx')],
            },
        ),
    ]
