"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-bi57rd=+m7mtaj&a$1no08il3zr*ie+=v)b+wosx_z#f&*pa_h',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local development; set DJANGO_DEBUG=False on the server.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

# Comma-separated list of hostnames the app is served under, e.g.
# DJANGO_ALLOWED_HOSTS=debtors.example.com,www.debtors.example.com
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Domains allowed to POST (Django requires this for HTTPS forms), e.g.
# DJANGO_CSRF_TRUSTED_ORIGINS=https://debtors.example.com
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Behind an HTTPS-terminating proxy / load balancer (the usual cloud setup),
# trust the forwarded-proto header and require secure cookies in production.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts',
    'xero_app',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Mirror the persisted Xero connection into each logged-in session so users
    # never have to re-"Connect to Xero" after logout / token expiry.
    'xero_app.middleware.XeroConnectionMiddleware',
    # Records every authenticated data-changing request to the Audit Log.
    'accounts.audit.AuditLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_engine = os.environ.get('DB_ENGINE', 'mssql').lower()

if _db_engine == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'FSA_Debtors'),
            'HOST': os.environ.get('DB_SERVER', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'USER': os.environ.get('DB_USER', 'fsa_debitor'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': os.environ.get('DB_NAME', 'FSA_Debtors'),
            'HOST': os.environ.get('DB_SERVER', r'localhost\SQLEXPRESS'),
            'PORT': os.environ.get('DB_PORT', ''),
            'USER': os.environ.get('DB_USER', ''),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'OPTIONS': {
                'driver': os.environ.get('DB_DRIVER', 'ODBC Driver 18 for SQL Server'),
                'extra_params': ('TrustServerCertificate=Yes'
                                 if os.environ.get('DB_USER')
                                 else 'TrustServerCertificate=Yes;Trusted_Connection=Yes'),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded files (invoice comment attachments)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# ---------------------------------------------------------------------------
# Email — sent via Microsoft Graph (app-only) from a shared mailbox
# ---------------------------------------------------------------------------
# All outbound mail (user onboarding, password resets, weekly reports, debtor
# reminders) goes through the Microsoft Graph sendMail API using an Entra app
# registration (client-credentials / Mail.Send application permission). This
# avoids SMTP, mailbox licensing and the basic-auth SMTP retirement entirely.
# A custom Django email backend routes EVERY Django email — including the
# built-in password-reset mail — through Graph, so features just use the normal
# Django mail helpers / xero_app.mailer.send_app_email().
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'xero_app.mail_backend.GraphEmailBackend')

MS_GRAPH_TENANT_ID = os.environ.get('MS_GRAPH_TENANT_ID', '')
MS_GRAPH_CLIENT_ID = os.environ.get('MS_GRAPH_CLIENT_ID', '')
MS_GRAPH_CLIENT_SECRET = os.environ.get('MS_GRAPH_CLIENT_SECRET', '')
# The mailbox (typically a shared mailbox) that mail is sent "from".
MS_GRAPH_SENDER = os.environ.get('MS_GRAPH_SENDER', '')

# Friendly From; Graph actually sends as MS_GRAPH_SENDER's mailbox identity.
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', MS_GRAPH_SENDER or 'no-reply@localhost')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Network timeout (seconds) for Graph token + sendMail calls.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))

# True when Graph email credentials are fully present — features that only make
# sense with live email (e.g. self-service password reset) can gate on this.
EMAIL_ENABLED = bool(MS_GRAPH_TENANT_ID and MS_GRAPH_CLIENT_ID
                     and MS_GRAPH_CLIENT_SECRET and MS_GRAPH_SENDER)

# Password-reset links stay valid for this long (seconds; default 3 days).
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', str(60 * 60 * 24 * 3)))

# Default recipients for system reports (e.g. the weekly lawyer/management
# digest) when a feature needs a fallback list. Comma-separated; optional.
REPORT_RECIPIENTS = [e.strip() for e in os.environ.get('REPORT_RECIPIENTS', '').split(',') if e.strip()]

# Public base URL used to build absolute links in emails (password-reset links,
# report deep-links) since outbound mail has no incoming request to derive it.
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://localhost:8000').rstrip('/')

# ---- WhatsApp (WATI) ----
# Powers the per-invoice WhatsApp reminder button. With these unset the button
# keeps its original behaviour: a wa.me link the user sends by hand.
# The newer "wati_..." tokens only work on the v3 tree and carry their own
# tenant, so the base URL has no tenant id in it.
WATI_BASE_URL = os.environ.get('WATI_BASE_URL', 'https://live-mt-server.wati.io/api/ext/v3').rstrip('/')
WATI_TOKEN = os.environ.get('WATI_TOKEN', '')

# Network timeout (seconds) for WATI calls.
WATI_TIMEOUT = int(os.environ.get('WATI_TIMEOUT', '20'))

# WATI accepts a send before Meta has judged it, so we read the conversation log
# back to catch a rejection. These bound that check: 3 tries, 1s apart, keeps a
# button click under ~3s while still catching the common failures.
WATI_VERIFY_ATTEMPTS = int(os.environ.get('WATI_VERIFY_ATTEMPTS', '3'))
WATI_VERIFY_DELAY = float(os.environ.get('WATI_VERIFY_DELAY', '1.0'))

# True when WhatsApp can actually send — templates gate on this to decide
# between the API button and the wa.me fallback.
WHATSAPP_ENABLED = bool(WATI_TOKEN and WATI_BASE_URL)
